### ISSUE TITLE
Hard crash when invalid language is specified

### ISSUE THREAD

**Issue by ghost** [philips-software/cerberus#15]
Example below (language=cs). Ideal would be to give message that language name is not supported and give a list of valid language names to the user at command line instead of hard crash-out with raw exception. Also, do you want language name to be case sensitive?

$ java -jar cerberus-executable.jar SWD --language=cs --files=.
java.lang.IllegalArgumentException: No enum constant com.philips.swcoe.cerberus.cerebellum.swd.SuppressedWarningDetectors.cs
        at java.base/java.lang.Enum.valueOf(Enum.java:240)
        at com.philips.swcoe.cerberus.cerebellum.swd.SuppressedWarningDetectors.valueOf(SuppressedWarningDetectors.java:11)
        at com.philips.swcoe.cerberus.hounds.SuppressedWarnings.call(SuppressedWarnings.java:50)
        at com.philips.swcoe.cerberus.hounds.SuppressedWarnings.call(SuppressedWarnings.java:30)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2141)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at com.philips.swcoe.cerberus.Cerberus.main(Cerberus.java:40)

**Comment by aravind666** [comment]
Thanks @simaos for reporting this , I have added the fix to one of the ongoing PR's  
It gets merged soon.
